# Generated by Django 3.2.20 on 2023-07-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20230705_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='user',
        ),
    ]
