# Generated by Django 3.2.20 on 2023-07-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_uploadedfiles_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
