# Generated by Django 3.2.20 on 2023-07-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_uploadedfiles_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
