# Generated by Django 3.2.20 on 2023-07-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_uploadedfiles_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
