# Generated by Django 3.2.20 on 2023-07-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
